-- Quests
-- 30019 doesn't work, add another quest custom quest item to use
-- buff 3 Tok'kar's weapons
-- NEXT 30020
-- A Lack of Fear (Fear Ward Quest)
UPDATE mangos . quest_template 
SET RequiredRaces = 0
WHERE entry IN(5641, 5645, 5647);

-- Rampaging Giants
UPDATE `mangos`.`quest_template` SET `RewRepValue1`=200 WHERE  `entry`=5981 AND `patch`=0;

-- Dustwallow Marsh
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30015, 15, 35, 45, 8, 'Deadmire', 'Me need giant Crocodile tooth. You bring.', 'Bring Deadmire\'s Tooth to Mudcrush Durtfeet in Swamp of Sorrows.', 'Me like. Me no eat you.', 'Me need Crocodile tooth.', '', '', '', '', '', 5945, 1, 10703, 10704, 1, 1, 3900, 1680);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (4503, 30015);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (4503, 30015);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemCount1`, `ReqItemCount2`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewItemCount1`, `RewItemCount2`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30016, 15, 38, 43, 8, 'Identifying the Brood', 'Me hate dragon. Me collect dragon parts. You bring.', 'Mudcrush Durtfeet would like you to bring him 15 Searing Tongues and 15 Searing Hearts.', 'Me best friend is you! Me never eat you.', 'Me hate dragon, want parts. ', '', '', '', '', '', 5840, 5841, 15, 15, 9703, 9704, 1, 1, 1, 1, 5350, 1680);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (4503, 30016);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (4503, 30016);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewItemCount1`, `RewItemCount2`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30017, 15, 38, 43, 8, 'Army of the Black Dragon', 'Me hate dragon. Dragon kill me wife. You kill dragon for me!', 'Mudcrush Durtfeet wants you to kill 15 Firemane Scouts, 10 Firemane Ash Tails, and 10 Firemane Guards.', 'Me feel avenged.', 'Dragon kill me wife!', '', '', '', '', '', 4329, 4331, 4328, 15, 10, 10, 9705, 9706, 1, 1, 1, 1, 3600, 1680);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (4503, 30017);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (4503, 30017);

REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30019, 15, 31, 41, 8, 'Mixology Ingredients I', 'I am running out of ingredients for mixology. Bring me 6 Acidic Venom Sac from Spiders in Swamp of Sorrows.', 'Bring Tabeta in Dustwallow Marsh  6 Acidic Venom Sac.', 'This will do.', 'Bring Tabeta in Dustwallow Marsh  6 Acidic Venom Sac.', '', '', '', '', '', 5959, 6, 2850, 1680);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (6546, 30019);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (6546, 30019);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30020, 15, 31, 41, 8, 'Mixology Ingredients II', 'I am running out of ingredients for mixology. Bring me 10 Daggermaw Crocolisk Skin from Drywallow Daggermaw in Swamp of Sorrows.', 'Bring Tabetha in Dustwallow Marsh 10 Daggermaw Crocolisk Skin from Drywallow Daggermaw in Swamp of Sorrows.', 'Very good.', 'Bring Tabetha in Dustwallow Marsh 10 Daggermaw Crocolisk Skin from Drywallow Daggermaw in Swamp of Sorrows.', '', '', '', '', '', 30044, 10, 3150, 1680);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (4345, 30044, -100);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (6546, 30020);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (6546, 30020);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewXP`, `RewMoneyMaxLevel`) VALUES (30021, 15, 31, 41, 8, 'Mixology Ingredients III', 'I am running out of ingredients for mixology. Bring me 10 Ooze Ichor from Swamp Ooze in Swamp of Sorrows.', 'Bring Tabetha in Dustwallow Marsh 10 Ooze Ichor from Swamp Ooze in Swamp of Sorrows.', 'I am pleased.', 'Bring Tabetha in Dustwallow Marsh 10 Ooze Ichor from Acidic Swamp Ooze in Swamp of Sorrows.', '', '', '', '', '', 30043, 10, 3150, 1680);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (4392, 30043, -100);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (4393, 30043, -100);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (6546, 30021);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (6546, 30021);

-- Swamp of Sorrows
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30009, 8, 35, 45, 8, 'Swamp Cleaning', 'Please, help me defend my camp from the beasts!', 'Kill 10 Marsh Inkspewers, 10 Marsh Flesheaters, and 10 Marsh Oracles, then return to Watcher Biggs in the Swamp of Sorrows.', 'The sounds of animals are now faint, more distant.  Thank you, $N.  Now let\'s hope they don\'t return!', 'Kill 10 Marsh Inkspewers, 10 Marsh Flesheaters, and 10 Marsh Oracles, then return to Watcher Biggs in the Swamp of Sorrows.', '', '', '', '', '', 750, 751, 752, 15, 15, 15, 72, 100, 3900, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30009);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30009);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30010, 8, 45, 55, 8, 'The Swamp Talker', 'A horde scout was taken away by the murlocs into the cave nearby. Recon says that the horde scout was carrying important documents. Find them and bring them back to me.', 'Retrieve the Warchief\'s Orders and return them to Watcher Biggs.', 'This should help us against the horde.', 'Retrieve the Warchief\'s Orders and return them to Watcher Biggs.', '', '', '', '', '', 8463, 1, 9680, 9678, 9679, 1, 1, 1, 72, 100, 5650, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30010);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30010);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30011, 8, 35, 44, 8, 'Fresh Meat', 'There\'s a high demand for the succulent taste of crawler meat among my customers; especially the meat from the monstrous crawlers.', 'Bring 10 Monstrous Crawler Legs to Watcher Biggs in the Swamp of Sorrows.', 'Thank you!', 'Bring 10 Monstrous Crawler Legs to Watcher Biggs in the Swamp of Sorrows.', '', '', '', '', '', 6184, 10, 72, 100, 3750, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30011);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30011);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30012, 8, 35, 42, 8, 'Lack of Surplus', 'The sawtooth snappers\' claws make for fine weapons when properly prepared. Bring me some of their claws and I\'ll see you\'re rewarded with one of our weapons in thanks for the fresh meat and the good company.', 'Bring 6 Sawtooth Snapper Claws to Watcher Biggs in the Swamp of Sorrows.', 'Excellent!', 'Bring 6 Sawtooth Snapper Claws to Watcher Biggs in the Swamp of Sorrows.', '', '', '', '', '', 6168, 6, 72, 100, 3450, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30012);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30012);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30013, 8, 32, 42, 8, 'Swamp Wildlife', 'Please, help me defend my camp from the spiders and panthers of the swamp.', 'Kill 10 Shadow Panthers and 30 Deathstrike Tarantaula\'s then return to Watcher Biggs in Swamp of Sorrows.', 'I can sleep much better knowing you have thinned the swamp of spiders and panthers. Thank you!', 'Kill 10 Shadow Panthers and 30 Deathstrike Tarantaula\'s then return to Watcher Biggs in Swamp of Sorrows.', '', '', '', '', '', 768, 769, 10, 30, 72, 100, 3500, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30013);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30013);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `RewMoneyMaxLevel`, `OfferRewardEmote1`) VALUES (30014, 8, 33, 43, 8, 'Dragonkin Eradication', 'I need your help in clearing the swamp of the Green Dragonkin.', 'Kill 20 Green Wyrmkin and 20 Wyrmkin Dreamwalker in Swamp of Sorrows.', 'You have done well.', 'Kill 20 Green Wyrmkin and 20 Wyrmkin Dreamwalker in Swamp of Sorrows.', '', '', '', '', '', 742, 743, 20, 20, 72, 100, 3700, 1740, 4);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5476, 30014);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5476, 30014);

-- Blasted Lands
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (8716, 30007, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (8717, 30007, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (8718, 30007, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (12396, 30007, 20);


REPLACE `mangos`.`faction` (`id`, `build`, `reputation_list_id`, `base_rep_race_mask1`, `base_rep_race_mask2`, `base_rep_race_mask3`, `base_rep_value1`, `base_rep_value2`, `base_rep_value3`, `reputation_flags1`, `reputation_flags2`, `name`, `description`) VALUES (476, 5302, 55, 73, 178, 4, 150, -42000, 500, 16, 22, 'Nethergarde Defenders', 'Stout defenders of the Dark Portal.');
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `hostile_mask`, `friend_faction1`) VALUES (1678, 4222, 476, 4, 471);
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `faction_flags`, `our_mask`, `friendly_mask`, `hostile_mask`, `friend_faction1`) VALUES (1679, 4222, 476, 2081, 3, 2, 12, 471);
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `faction_flags`, `our_mask`, `friendly_mask`, `hostile_mask`, `friend_faction1`) VALUES (1680, 4222, 476, 33, 2, 2, 4, 471);

UPDATE `mangos`.`creature_template` SET `faction`=1678 WHERE  `entry`=5385 AND `patch`=0;
UPDATE `mangos`.`creature_template` SET `faction`=1678 WHERE  `entry`=5393 AND `patch`=0;
REPLACE `mangos`.`quest_template` (`entry`, `Method`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `SpecialFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `IncompleteEmote`, `CompleteEmote`) VALUES (30000, 0, 4, 58, 62, 264, 1, 'Demon Bounty', '', '', 'Please bring me more demon cores.', 'Please bring me more demon cores.', '', '', '', '', '', 30007, 5, 476, 150, 390, 25, 1, 1);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5385, 30000);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5385, 30000);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `SuggestedPlayers`, `QuestFlags`, `SpecialFlags`, `ExclusiveGroup`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`) VALUES (30001, 4, 58, 62, 5, 8, 1, 0, 'Legion Clean Up', 'Thin the lines of the Legion and help us push them back!', 'Kill 20 Felguard Elites, 10 Doomguard Commanders, and 3 Dreadlords then return to Watcher Mahar Ba.', 'Well done $N. Maybe we will live for another day.', 'The Legion must fall!', '', '', '', '', '', 8717, 12396, 8716, 20, 5, 5, 476, 250, 5800, 1, 1, 1, 5, 5, 1, 1, 5);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5385, 30001);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5385, 30001);
REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `SuggestedPlayers`, `QuestFlags`, `SpecialFlags`, `ExclusiveGroup`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`) VALUES (30002, 4, 58, 62, 5, 8, 1, 0, 'Manahound Round Up', 'Clear out Mana Hounds.', 'Annihilate 50 Mana Hounds.', 'Well done $N. Maybe we will live for another day.', 'The Legion must fall!', '', '', '', '', '', 8718, 50, 476, 250, 5800, 1, 1, 1, 5, 5, 1, 1, 5);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (5385, 30002);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (5385, 30002);

-- Deadwind Pass
REPLACE `mangos`.`faction` (`id`, `build`, `reputation_list_id`, `base_rep_race_mask1`, `base_rep_race_mask2`, `base_rep_race_mask3`, `base_rep_value1`, `base_rep_value2`, `base_rep_value3`, `reputation_flags1`, `reputation_flags2`, `name`, `description`) VALUES (477, 5302, 56, 73, 178, 4, 150, -42000, 500, 16, 22, 'Caretakers of Karazhan', 'Medivh\'s personal caretakers.');
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `hostile_mask`, `friend_faction1`) VALUES (1681, 4222, 477, 4, 471);
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `faction_flags`, `our_mask`, `friendly_mask`, `hostile_mask`, `friend_faction1`) VALUES (1682, 4222, 477, 2081, 3, 2, 12, 471);
REPLACE `mangos`.`faction_template` (`id`, `build`, `faction_id`, `faction_flags`, `our_mask`, `friendly_mask`, `hostile_mask`, `friend_faction1`) VALUES (1683, 4222, 477, 33, 2, 2, 4, 471);

-- REPLACE `mangos`.`creature_template` (`entry`, `name`, `subname`, `level_min`, `level_max`, `faction`, `npc_flags`, `display_id1`, `display_probability1`, `display_total_probability`, `health_multiplier`, `damage_multiplier`, `base_attack_time`, `fire_res`, `arcane_res`, `unit_class`, `unit_flags`, `type`, `ai_name`, `equipment_id`, `flags_extra`) VALUES (90035, 'Maximillian Arturo', 'Caretaker of Karazhan', 58, 58, 1681, 2, 1724, 1, 1, 3, 0.8, 1000, 100, 100, 1, 4096, 7, '', 264, 524296);
REPLACE INTO `creature_template` 
(`entry`, `name`, `subname`, `level_min`, `level_max`, `faction`, `npc_flags`, `display_id1`, `display_probability1`, `display_total_probability`, `health_multiplier`, `damage_multiplier`, `base_attack_time`, `fire_res`, `arcane_res`, `unit_class`, `type`, `ai_name`, `equipment_id`, `flags_extra`) 
VALUES 
(90035, 'Maximillian Arturo', 'Caretaker of Karazhan', 58, 58, 1681, 2, 1724, 1, 1, 3, 0.8, 1000, 100, 100, 1, 7, '', 264, 524296);

REPLACE `mangos`.`creature` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `wander_distance`) VALUES (2000037, 90035, 0, -10451.66, -1720.62, 85.05, 1.8897, 0);
-- REPLACE `mangos`.`creature_template` (`entry`, `name`, `subname`, `level_min`, `level_max`, `faction`, `npc_flags`, `display_id1`, `display_probability1`, `display_total_probability`, `health_multiplier`, `damage_multiplier`, `base_attack_time`, `fire_res`, `arcane_res`, `unit_class`, `unit_flags`, `type`, `ai_name`, `equipment_id`, `flags_extra`) VALUES (90036, 'Wade Wells', 'Caretaker of Karazhan', 58, 58, 1681, 4, 10591, 1, 1, 3, 0.8, 1000, 100, 100, 1, 4096, 7, '', 264, 524296);
REPLACE INTO `creature_template` 
(`entry`, `name`, `subname`, `level_min`, `level_max`, `faction`, `npc_flags`, `display_id1`, `unit_class`, `flags_extra`) 
VALUES 
(90036, 'Wade Wells', 'Caretaker of Karazhan', 58, 58, 1681, 4, 10591, 1, 524296);

REPLACE `mangos`.`creature` (`guid`, `id`, `map`, `position_x`, `position_y`, `position_z`, `orientation`, `wander_distance`) VALUES (2000038, 90036, 0, -10453.53, -1721.077, 84.94, 1.8964, 0);

REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `SuggestedPlayers`, `QuestFlags`, `SpecialFlags`, `ExclusiveGroup`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`) VALUES (30003, 41, 58, 60, 5, 8, 1, 0, 'Clear the Crypts', 'Rid the Crypts underneath Karazhan of Damned Souls, and Wailing Spectres.', 'Kill 25 Damned Souls and 25 Wailing Spectres.', 'Well done $N. Now the ghostly presence should be lowered.', 'Karazhan is all I care about.', '', '', '', '', '', 12378, 12377, 25, 25, 477, 250, 5800, 1, 1, 1, 5, 5, 1, 1, 5);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30003);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30003);

REPLACE `mangos`.`quest_template` (`entry`, `Method`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `SpecialFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `IncompleteEmote`, `CompleteEmote`) VALUES (30004, 0, 41, 58, 62, 264, 1, 'Ectoplasm Collection', '', '', 'Please bring me Ghost Ectoplasm from the Unliving near Karazhan.', 'Please bring me Ghost Ectoplasm from the Unliving near Karazhan.', '', '', '', '', '', 30016, 5, 477, 150, 390, 25, 1, 1);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30004);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30004);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (12379, 30016, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (12380, 30016, 20);

REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `SuggestedPlayers`, `QuestFlags`, `SpecialFlags`, `ExclusiveGroup`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`) VALUES (30005, 41, 58, 60, 5, 8, 1, 0, 'Exorcise the Unliving', 'Kill the Unliving Residents and Unliving Caretakers near Karazhan.', 'Kill 25 Unliving Residents and 25 Unliving Caretakers.', 'Well done $N. Now the ghostly presence should be lowered.', 'Karazhan is all I care about.', '', '', '', '', '', 12380, 12379, 25, 25, 477, 250, 5800, 1, 1, 1, 5, 5, 1, 1, 5);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30005);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30005);

REPLACE `mangos`.`quest_template` (`entry`, `Method`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `SpecialFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `IncompleteEmote`, `CompleteEmote`) VALUES (30006, 0, 41, 58, 62, 264, 1, 'Shade Dust', '', '', 'Bring me Shade Dust from the Restless Shades in the crypts underneath Karazhan.', 'Please bring me Shade Dust from the Restless Shades in the crypts underneath Karazhan.', '', '', '', '', '', 30017, 25, 477, 150, 390, 25, 1, 1);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30006);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30006);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (7370, 30017, 100);

REPLACE `mangos`.`quest_template` (`entry`, `Method`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `QuestFlags`, `SpecialFlags`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemCount1`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `IncompleteEmote`, `CompleteEmote`) VALUES (30007, 0, 41, 58, 62, 264, 1, 'Ogre Beads', '', '', 'Bring me Ogre Beads from the Deadwind Ogres ', 'Bring me Ogre Beads from the Deadwind Ogres.', '', '', '', '', '', 30018, 10, 477, 150, 390, 25, 1, 1);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30007);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30007);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (7372, 30018, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (7371, 30018, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (7379, 30018, 20);
REPLACE `mangos`.`creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`) VALUES (7369, 30018, 20);

REPLACE `mangos`.`quest_template` (`entry`, `ZoneOrSort`, `MinLevel`, `QuestLevel`, `SuggestedPlayers`, `QuestFlags`, `SpecialFlags`, `ExclusiveGroup`, `Title`, `Details`, `Objectives`, `OfferRewardText`, `RequestItemsText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqCreatureOrGOId1`, `ReqCreatureOrGOId2`, `ReqCreatureOrGOId3`, `ReqCreatureOrGOCount1`, `ReqCreatureOrGOCount2`, `ReqCreatureOrGOCount3`, `RewRepFaction1`, `RewRepValue1`, `RewXP`, `DetailsEmote1`, `DetailsEmote2`, `DetailsEmote3`, `IncompleteEmote`, `CompleteEmote`, `OfferRewardEmote1`, `OfferRewardEmote2`, `OfferRewardEmote3`) VALUES (30008, 41, 58, 60, 5, 8, 1, 0, 'Ogre Round Up', 'Kill 20 Deadwind Warlocks, 10 Deadwind Maulers and 20 Deadwind Ogre Mages.', 'Kill 20 Deadwind Warlocks, 10 Deadwind Maulers and 20 Deadwind Ogre Mages.', 'Well done $N. Those Ogres must be pushed out of Deadwind Pass.', 'Karazhan is all I care about.', '', '', '', '', '', 7372, 7371, 7379, 20, 10, 20, 477, 250, 5800, 1, 1, 1, 5, 5, 1, 1, 5);
REPLACE `mangos`.`creature_questrelation` (`id`, `quest`) VALUES (90035, 30008);
REPLACE `mangos`.`creature_involvedrelation` (`id`, `quest`) VALUES (90035, 30008);
